---
title: "R Notebook"
output: html_notebook
---
```{r}
source("functions.R")
```

```{r}
library(mvtnorm)
```

Creation of the grid

```{r}
env_lat<-data.matrix(read.table("depo_latemar.txt"))
grid<-array(NA,c(100,10,91))
grid[5,2,]<-env_lat[,1]
grid[25,5,]<-env_lat[,2]
grid[35,8,]<-env_lat[,3]
grid[95,3,]<-env_lat[,4]

```
```{r}
e1<-e2<-e3<-e4<-matrix(0,91,4)
e1[env_lat==1]=1
e2[env_lat==2]=1
e3[env_lat==3]=1
e4[env_lat==4]=1
pe1 = mean(e1,na.rm=TRUE)
pe2 = mean(e2,na.rm=TRUE)
pe3 = mean(e3,na.rm=TRUE)
pe4 = mean(e4,na.rm=TRUE)
c(pe1,pe2,pe3,pe4)
```

```{r}
q1=qnorm(pe1+pe2)
Sigma1 = matrix(c(1,rho,rho,1),2,2)
q2=0
obj = Inf
for ( test in 1:100 ){
  q2test = qnorm(test/100)
  newobj =abs( pmvnorm(lower=c(-Inf,-Inf),upper=c(q1,q2test),mean=c(0,0),sigma=Sigma1) - pe1 ) 
  if (newobj < obj){
    q2 = q2test
    obj = newobj
  }
}
q3=0
obj = Inf
for ( test in 1:100 ){
  q3test = qnorm(test/100)
  newobj =abs( pmvnorm(lower=c(q1,-Inf),upper=c(Inf,q3test),mean=c(0,0),sigma=Sigma1) - pe4 ) 
  if (newobj < obj){
    q3 = q3test
    obj = newobj
  }
}
c(q1,q2,q3)
```


```{r}
q1=qnorm(pe1+pe2)
Sigma1 = matrix(c(1,rho,rho,1),2,2)
q2=0
obj = Inf
for ( test in 1:100 ){
  q2test = qnorm(test/100)
  newobj =abs( pmvnorm(lower=c(-Inf,-Inf),upper=c(q1,q2test),mean=c(0,0),sigma=Sigma1) - pe1 ) 
  if (newobj < obj){
    q2 = q2test
    obj = newobj
  }
}
q3=0
obj = Inf
for ( test in 1:100 ){
  q3test = qnorm(test/100)
  newobj =abs( pmvnorm(lower=c(q1,-Inf),upper=c(Inf,q3test),mean=c(0,0),sigma=Sigma1) - pe4 ) 
  if (newobj < obj){
    q3 = q3test
    obj = newobj
  }
}

```

```{r}
model<-function(h,range,b){return(exp(-(h/range)^2)*cos(b*h))}
```

```{r}
rho=0.8
shift=0.1
rho1a=model(shift,0.3,0)
Z1<-sim3d(0.3,100,0,100,0.1,91,5,100,10,10)
Z2<-sim3d(1.2,100,5,100,0.1,91,5,100,10,10)
for ( z in 1:90){
  Z2[,,z]=Z2[,,z]*sqrt(1-(rho^2)/(rho1a^2))+Z1[,,z+1]*(rho)/(rho1a)
}
```

```{r}
faciesenv<-Z1
faciesenv[Z1<q1 & Z2<q2]=1
faciesenv[Z1<q1 & Z2>q2]=2
faciesenv[Z1>q1 & Z2<q3]=4
faciesenv[Z1>q1 & Z2>q3]=3
```

```{r}
for ( z in 1:91){
  for ( y in 1:10){
    for ( x in 1:100){
      write(toString(c(faciesenv[x,y,z])),"latemaruncondrythm.csv",append=TRUE)
    }
  }
}
```

we want now to compare the experimental transiograms to the one simulated
```{r}
csime1<-csime2<-csime3<-csime4<-array(0,c(100,10,91))
csime1[faciesenv==1]=1
csime2[faciesenv==2]=1
csime3[faciesenv==3]=1
csime4[faciesenv==4]=1
```


```{r}
par(mfrow=c(3,3))
nz=91
z = (1:30)/10.
t11<-tr_2d_vert(e1,e1,30,nz,0.1)
t11sim<-tr_3d_vert(sime1,sime1,30,nz,0.1)
bt11sim<-tr_3d_vert(bsime1,bsime1,30,nz,0.1)
ct11sim<-tr_3d_vert(csime1,csime1,30,nz,0.1)
lines(z,t11sim)
lines(z,bt11sim)
lines(z,ct11sim)
t12<-tr_2d_vert(e1,e2,30,nz,0.1)
t12sim<-tr_3d_vert(sime1,sime2,30,nz,0.1)
bt12sim<-tr_3d_vert(bsime1,bsime2,30,nz,0.1)
ct12sim<-tr_3d_vert(csime1,csime2,30,nz,0.1)
lines(z,t12sim)
lines(z,bt12sim)
lines(z,ct12sim)
t13<-tr_2d_vert(e1,e3,30,nz,0.1)
t13sim<-tr_3d_vert(sime1,sime3,30,nz,0.1)
bt13sim<-tr_3d_vert(bsime1,bsime3,30,nz,0.1)
ct13sim<-tr_3d_vert(csime1,csime3,30,nz,0.1)
lines(z,t13sim)
lines(z,bt13sim)
lines(z,ct13sim)
t21<-tr_2d_vert(e2,e1,30,nz,0.1)
t21sim<-tr_3d_vert(sime2,sime1,30,nz,0.1)
bt21sim<-tr_3d_vert(bsime2,bsime1,30,nz,0.1)
ct21sim<-tr_3d_vert(csime2,csime1,30,nz,0.1)
lines(z,t21sim)
lines(z,bt21sim)
lines(z,ct21sim)
t22<-tr_2d_vert(e2,e2,30,nz,0.1)
t22sim<-tr_3d_vert(sime2,sime2,30,nz,0.1)
bt22sim<-tr_3d_vert(bsime2,bsime2,30,nz,0.1)
ct22sim<-tr_3d_vert(csime2,csime2,30,nz,0.1)
lines(z,t22sim)
lines(z,bt22sim)
lines(z,ct22sim)
t23<-tr_2d_vert(e2,e3,30,nz,0.1)
t23sim<-tr_3d_vert(sime2,sime3,30,nz,0.1)
bt23sim<-tr_3d_vert(bsime2,bsime3,30,nz,0.1)
ct23sim<-tr_3d_vert(csime2,csime3,30,nz,0.1)
lines(z,t23sim)
lines(z,bt23sim)
lines(z,ct23sim)
t31<-tr_2d_vert(e3,e1,30,nz,0.1)
t31sim<-tr_3d_vert(sime3,sime1,30,nz,0.1)
bt31sim<-tr_3d_vert(bsime3,bsime1,30,nz,0.1)
ct31sim<-tr_3d_vert(csime3,csime1,30,nz,0.1)
lines(z,t31sim)
lines(z,bt31sim)
lines(z,ct31sim)
t32<-tr_2d_vert(e3,e2,30,nz,0.1)
t32sim<-tr_3d_vert(sime3,sime2,30,nz,0.1)
bt32sim<-tr_3d_vert(bsime3,bsime2,30,nz,0.1)
ct32sim<-tr_3d_vert(csime3,csime2,30,nz,0.1)
lines(z,t32sim)
lines(z,bt32sim)
lines(z,ct32sim)
t33<-tr_2d_vert(e3,e3,30,nz,0.1)
t33sim<-tr_3d_vert(sime3,sime3,30,nz,0.1)
bt33sim<-tr_3d_vert(bsime3,bsime3,30,nz,0.1)
ct33sim<-tr_3d_vert(csime3,csime3,30,nz,0.1)
lines(z,t33sim)
lines(z,bt33sim)
lines(z,ct33sim)
```

